name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: submodule update
        run: git submodule update --init --recursive

      - name: Install libarchive
        run: sudo apt-get install libarchive-dev

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Build release for Linux
        run: zig build -Dtarget=x86_64-linux

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zvm-linux
          path: zig-out/bin

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: submodule update
        run: git submodule update --init --recursive

      - name: Install libarchive
        run: |
          brew install automake autoconf
          make libarchive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Build release for MacOS
        run: zig build -Dtarget=x86_64-macos

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zvm-macos
          path: zig-out/bin

  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Linux artifact
      uses: actions/download-artifact@v2
      with:
        name: zvm-linux
        path: artifacts/

    - name: Download MacOS artifact
      uses: actions/download-artifact@v2
      with:
        name: zvm-macos
        path: artifacts/

    - name: Create and Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/zvm-linux,artifacts/zvm-macos"
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
